<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VOQUA57D" failures="1" tests="3" name="EdgeTest" time="9.129" errors="0" timestamp="2023-11-13T00:10:49 IST">
  <testcase classname="com.mystore.testcases.LoginPageTest" name="loginTest" time="0.717"/>
  <testcase classname="com.mystore.testcases.LoginPageTest" name="loginTest" time="0.476">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at com.mystore.testcases.LoginPageTest.loginTest(LoginPageTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mystore.testcases.LoginPageTest" name="verifyTitle" time="0.01"/>
</testsuite> <!-- EdgeTest -->
